services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: spynet_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db 
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.front
    container_name: spynet_frontend
    restart: always
    ports: 
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    container_name: spynet_postgres_db
    restart: always
    environment:
      POSTGRES_DB: spynet-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d spynet-db"]
      interval: 5s
      timeout: 3s
      retries: 5
      

    

volumes:
  postgres_data:
