# Generated by Django 5.2.15 on 2026-06-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('technologies', models.JSONField(default=list)),
                ('dns', models.JSONField(blank=True, null=True)),
                ('whois', models.JSONField(blank=True, null=True)),
                ('geo', models.JSONField(blank=True, null=True)),
                ('wayback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
