# Generated by Django 5.2.15 on 2026-06-29 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2000)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('partial', 'partial'), ('failed', 'failed')], default='completed', max_length=20)),
                ('triggered_by', models.CharField(choices=[('api', 'api'), ('snapshot', 'snapshot'), ('cli', 'cli')], default='api', max_length=20)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='api.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='DnsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolver', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dns_result', to='api.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=500)),
                ('ttl', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('dns_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.dnsresult')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.domain'),
        ),
        migrations.CreateModel(
            name='GeoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=8, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('asn', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_record', to='api.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='WaybackResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_count', models.PositiveIntegerField(default=0)),
                ('archive_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('first_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('last_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wayback_result', to='api.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='WaybackSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=2000)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('wayback_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.waybackresult')),
            ],
        ),
        migrations.CreateModel(
            name='WhoisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('registrant', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('domain_age_years', models.FloatField(blank=True, null=True)),
                ('status_flags', models.JSONField(blank=True, null=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whois_record', to='api.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('cdn', 'cdn'), ('server', 'server')], max_length=20)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('evidence', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='api.analysis')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='api.waybacksnapshot')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('analysis__isnull', False), ('snapshot__isnull', True)), models.Q(('analysis__isnull', True), ('snapshot__isnull', False)), _connector='OR'), name='technology_exactly_one_parent')],
            },
        ),
    ]
