# Generated by Django 5.2.15 on 2026-06-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='triggered_by',
            field=models.CharField(choices=[('api', 'api'), ('snapshot', 'snapshot'), ('historical', 'historical'), ('cli', 'cli')], default='api', max_length=20),
        ),
    ]
