# Generated by Django 5.2.15 on 2026-06-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_analysis_triggered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('cdn', 'cdn'), ('server', 'server'), ('analytics', 'analytics')], max_length=20),
        ),
    ]
