# Generated by Django 5.2.15 on 2026-07-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_technology_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='tls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='georecord',
            name='reverse_dns',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whoisrecord',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whoisrecord',
            name='dnssec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whoisrecord',
            name='emails',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whoisrecord',
            name='org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
