# Generated by Django 5.2.15 on 2026-07-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_analysis_tls_georecord_reverse_dns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='security',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
