# Generated by Django 5.2.15 on 2026-07-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_analysis_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='email_security',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
