VALIDATION_ERROR = "VALIDATION_ERROR"
NOT_FOUND = "NOT_FOUND"
METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
RATE_LIMITED = "RATE_LIMITED"
EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
MISSING_QUESTION = "MISSING_QUESTION"
MISSING_ANALYSIS = "MISSING_ANALYSIS"

# Fuente única para el `enum` de `error.code` en el esquema OpenAPI.
ALL = (
    VALIDATION_ERROR,
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    RATE_LIMITED,
    EXTERNAL_SERVICE_ERROR,
    INTERNAL_ERROR,
    MISSING_QUESTION,
    MISSING_ANALYSIS,
)
